// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.sau.sausensor.server.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Mts400ResultsL_Roo_Configurable {

    declare @type: Mts400ResultsL: @Configurable;

}
